### ISSUE TITLE
Encrypt messages between algorithms (java)

### ISSUE THREAD

**Issue by dsmits** [CARRIER-project/verticox#4]

**Comment by fvandaalen** [comment]
n-party protocol internally uses AES, but the key is a java-class (SecretKeySpec).
Key is included as a sequence of bytes, alongside the name of the used algorithm as a string.

Can this be communicated to python?

**Comment by fvandaalen** [comment]
Implemented AES and RSA on java side. Same approach as used in the n-party protocol
